### ISSUE TITLE
Textualizer: LionWeb.Core.UnsetFeatureException

### ISSUE THREAD

**Issue by erk-dik** [LionWeb-io/lionweb-csharp#7]
`Textualizer.AsString(node); ` throws the following exception:

```
  LionWeb.Core.UnsetFeatureException
  Required Property name is not set
...
   at LionWeb.Core.Utilities.Textualizer.<AsStrings>g__ReferenceTargetAsString|4_2(INode target)
   at System.Linq.Enumerable.SelectIListIterator`2.Fill(IList`1 source, Span`1 results, Func`2 func)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at LionWeb.Core.Utilities.Textualizer.Join(IEnumerable`1 strings, String separator)
   at LionWeb.Core.Utilities.Textualizer.<>c__DisplayClass4_0.<AsStrings>g__ReferenceAsString|3(Reference reference)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at LionWeb.Core.Utilities.Textualizer.AsStrings(INode node)
   at LionWeb.Core.Utilities.Textualizer.AsString(INode node)
...
```

**Comment by dslmeinte** [comment]
@erk-dik Can you implement a failing unit test for this somewhere?

**Comment by dslmeinte** [comment]
@erk-dik @JojoEffect Should be fixed by PR #10 .

**Comment by dslmeinte** [comment]
@erk-dik Can I make you collaborator of this repo? Then I can request reviews of PRs from you.

**Comment by erk-dik** [comment]
Sure  @dslmeinte

**Comment by dslmeinte** [comment]
> Sure @dslmeinte

Invite sent :)
